//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> Year { get; set; }
        public int DirectorId { get; set; }
        public Nullable<int> LeadingActorId { get; set; }
        public Nullable<int> LeadingActressId { get; set; }
        public int StudioId { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Actress Actress { get; set; }
        public virtual Director Director { get; set; }
        public virtual Studio Studio { get; set; }
    }
}
